# development:
#   cloud_name: "doxb1ih4o"
#   api_key: "982788521515834"
#   api_secret: "NDyjawZnA1KKD98pMGSUQ4_ot4A"
#   secure: true

# production:
#   cloud_name: "doxb1ih4o"
#   api_key: "982788521515834"
#   api_secret: "NDyjawZnA1KKD98pMGSUQ4_ot4A"
#   secure: true
